apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hh7l0wbph-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hh7l0wbph-java-springboot-gitops